#!/usr/bin/env bash

# Parse the Apache log file and group visitors by IP and HTTP status code using awk
awk '{ count[$1" "$9]++ } END { for (item in count) print count[item], item }' /path/to/apache_log_file | sort -rn
