#!/usr/bin/env bash
#loop 10 iterations and three especific conditionals
counter=1

while [ $counter -le 10 ]; do
    if [ $counter -eq 4 ]; then
        echo "Condition 1: $counter"
    elif [ $counter -eq 7 ]; then
        echo "Condition 2: $counter"
    elif [ $counter -eq 9 ]; then
        echo "Condition 3: $counter"
    else
        echo "Default condition: $counter"
    fi
    counter=$((counter + 1))
done
